#!/bin/sh

#$ -cwd
#$ -l long
#$ -pe smp 10

if [ -d $HOME/.usr/bin ] ; then
    export PATH=$HOME/.usr/bin:$PATH
    export CPATH=$HOME/.usr/include
    export LD_LIBRARY_PATH=$HOME/.usr/lib:$LD_LIBRARY_PATH
    export LIBRARY_PATH=$LD_LIBRARY_PATH
    export PYTHONPATH=$HOME/.usr/lib/python2.6/site-packages/
fi

echo "starting the job on $(hostname)"

set -x

./ucsc-dromel-multiz15-FBgn0013686.sh
