#! /usr/bin/env python

# Copyright (C) 2012 Philipp Benner
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# imports
# ------------------------------------------------------------------------------

import getopt
import re
import sys

from Bio         import AlignIO
from Bio.AlignIO import MafIO

# usage
# ------------------------------------------------------------------------------

def usage():
    """Print usage."""
    print
    print "macs2multiz [option]... MACS_FILE"
    print
    print "Options:"
    print "   -d                             - directory containing multiz alignments"
    print "   -f                             - output format [default: maf]"
    print "   -r                             - reference sequence [default: hg18]"
    print
    print "   -h, --help                     - print help"
    print "   -v, --verbose                  - be verbose"
    print

# options
# ------------------------------------------------------------------------------

options = {
    'database_dir'  : None,
    'macs_file'     : None,
    'refseq'        : 'hg18',
    'output_format' : 'maf',
    'verbose'       : False,
    }

# macs2multiz
# ------------------------------------------------------------------------------

def get_alignment(chromosome, seq_start, seq_end):
    if options['database_dir']:
        mafindex   = "%s/%s.mafindex" % (options['database_dir'], chromosome)
        maf        = "%s/%s.maf"      % (options['database_dir'], chromosome)
    else:
        mafindex   = "%s.mafindex" % chromosome
        maf        = "%s.maf"      % chromosome
    seqname = "%s.%s" % (options['refseq'], chromosome)

    idx = MafIO.MafIndex(mafindex, maf, seqname)

    multiple_alignment = idx.get_spliced([seq_start],
                                         [seq_end],
                                         strand = "+")

    AlignIO.write(multiple_alignment, sys.stdout, options['output_format'])


def parse_macs():
    fp = open(options['macs_file'], 'r')
    pattern = re.compile('^(chr[XY0-9]+)[ \t]([0-9]+)[ \t]([0-9]+)')

    for line in fp:
        m = pattern.match(line)
        if m:
            get_alignment(m.group(1), int(m.group(2)), int(m.group(3)))

    fp.close()

# main
# ------------------------------------------------------------------------------

def main():
    global options
    try:
        longopts   = ["help", "verbose"]
        opts, tail = getopt.getopt(sys.argv[1:], "d:f:r:hv", longopts)
    except getopt.GetoptError:
        usage()
        return 2
    output = None
    if len(tail) != 1:
        usage()
        return 1
    # override those options with command line arguments
    for o, a in opts:
        if o in ("-v", "--verbose"):
            sys.stderr.write("Verbose mode turned on.\n")
            options["verbose"] = True
        if o in ("-h", "--help"):
            usage()
            return 0
        if o == "-d":
            options['database_dir'] = a
        if o == "-f":
            options['output_format'] = a
        if o == "-r":
            options['refseq'] = a
    # tail
    options['macs_file'] = tail[0]
    # parse macs file and exit
    parse_macs()
    return 0

if __name__ == "__main__":
    sys.exit(main())
