#! /usr/bin/env python

# Copyright (C) 2012 Philipp Benner
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# imports
# ------------------------------------------------------------------------------

import getopt
import re
import sys

import Queue
import threading
import thread

from Bio                    import AlignIO

from tfbayes.phylotree      import *
from tfbayes.uipac.alphabet import DNA

# usage
# ------------------------------------------------------------------------------

def usage():
    """Print usage."""
    print
    print "tfbayes-approximate [option]... PHYLOGENETIC_TREE INPUT_FILE..."
    print
    print "Given a set of alignments from the ChIP experiment, this"
    print "program computes an approximation of the phylogenetic tree"
    print "for each column of the multiple alignment. The result is"
    print "used as input for the sampler."
    print
    print "Options:"
    print "       --format=STR       - format of the input file(s) (fasta or maf)"
    print "                            [default: maf]"
    print
    print "   -t, --threads=N        - run N jobs in parallel"
    print "   -s SPECIES             - remove all columns have no nucleotide"
    print "                            in this SPECIES"
    print
    print "   -h, --help             - print help"
    print "   -v, --verbose          - be verbose"
    print

# options
# ------------------------------------------------------------------------------

options = {
    'phylotree'      : None,
    'leafmap'        : None,
    'strip'          : None,
    'format'         : 'maf',
    'threads'        : 1,
    'verbose'        : False,
    }

# some tools
# ------------------------------------------------------------------------------

def print_result(container):
    print '>%s' % os.path.basename(container['file_name'])
    for result in container['result']:
        for i in range(5):
            print '%11.8f' % result[i],
        print ";"

def code_nucleotide(char):
    if char == 'N' or char == 'n' or char == "-":
        return 4.0
    else:
        return float(DNA.code(char))

# main logic comes here
# ------------------------------------------------------------------------------

def alignment_approximate(multiple_alignment, phylotree):
    """For every column in the alignment, approximate the likelihood
    given by the phylogenetic tree by a simple multinomial
    distribution with averaged count statistics."""
    leafmap   = options['leafmap']
    num_leafs = pt_num_leafs(phylotree)

    observations = [ 4.0 ]*num_leafs

    # index of the sequence from which to strip all dashes
    stripindex = None
    # search the multiple alignment for this index
    if options['strip']:
        for i in range(len(multiple_alignment)):
            name = multiple_alignment[i].name.split(".")[0]
            if options['strip'] == name:
                stripindex = i
        if stripindex == None:
            sys.stderr.write("Species `%s' not found in the alignment.\n" % options['strip'])

    result = []
    for i in range(len(multiple_alignment[0])):
        # filter all positions where the reference sequence has a gap
        if not stripindex == None and multiple_alignment[stripindex][i] == '-':
            continue
        # fill observations array
        for alignment in multiple_alignment:
            name = alignment.name.split(".")[0]
            if leafmap.has_key(name):
                observations[leafmap[name]] = code_nucleotide(alignment.seq[i])
        # call phylotree library
        result.append(pt_approximate(phylotree, observations))
    return result

# parse fasta file
# ------------------------------------------------------------------------------

def get_alignment(file_name):
    # use biopython to parse the alignment file
    if options['format'] == 'maf':
        return AlignIO.parse(file_name, options['format'])
    else:
        return AlignIO.read(file_name, options['format'])

# threading
# ------------------------------------------------------------------------------

class ComputationThread(threading.Thread):
    def __init__(self, queue_in, queue_out, mutex):
        threading.Thread.__init__(self)
        self.queue_in  = queue_in
        self.queue_out = queue_out
        self.mutex     = mutex
        self.phylotree = pt_clone(options['phylotree'])
    def __del__(self):
        pt_destroy(self.phylotree)
    def run(self):
        while True:
            job = self.queue_in.get()
            if options['verbose']:
                # to print a message we need to acquire the mutex
                # to messages to not appear scrambled
                self.mutex.acquire()
                print >> sys.stderr, 'Processing %s sequence %d.' % (job['file_name'], job['id'])
                self.mutex.release()
            # turn the alignment into an approximation
            result    = alignment_approximate(job['alignment'], self.phylotree)
            if result:
                container = {
                    'result'       : result,
                    'file_name'    : job['file_name'],
                    'id'           : job['id'] }
                self.queue_out.put((job['id'], container))
            self.queue_in.task_done()

def launch_threads(jobs):
    mutex     = thread.allocate_lock()
    queue_in  = Queue.Queue()
    queue_out = Queue.PriorityQueue()
    threads   = []
    # launch daemon threads
    if not threads:
        for i in range(options['threads']):
            t = ComputationThread(queue_in, queue_out, mutex)
            t.setDaemon(True)
            t.start()
            threads += [t]
    # fill input queue
    for job in jobs:
        queue_in.put(job)
    queue_in.join()
    # process output
    while not queue_out.empty():
        container = queue_out.get()[1]
        print_result(container)

# go through the list of fasta files and package them nicely as jobs
# ------------------------------------------------------------------------------

def main_fasta(files):
    jobs = []
    for idx, fasta_file in enumerate(files):
        job = {
            'file_name' : fasta_file,
            'alignment' : get_alignment(fasta_file),
            'id'        : idx }
        jobs.append(job)

    launch_threads(jobs)

def main_maf(files):
    jobs = []
    n    = 0
    for maf_file in files:
        alignment_list = get_alignment(maf_file)
        # maf files usually contain multiple alignment blocks
        for alignment in alignment_list:
            n = n + 1
            job = {
                'file_name' : maf_file,
                'alignment' : alignment,
                'id'        : n }
            jobs.append(job)

    launch_threads(jobs)

# main
# ------------------------------------------------------------------------------

def __main__():
    global options
    try:
        longopts   = ["format=", "threads=", "help", "verbose"]
        opts, tail = getopt.getopt(sys.argv[1:], "s:t:hv", longopts)
    except getopt.GetoptError:
        usage()
        return 2
    output = None
    if len(tail) < 2:
        usage()
        return 1
    # override those options with command line arguments
    for o, a in opts:
        if o in ("-v", "--verbose"):
            sys.stderr.write("Verbose mode turned on.\n")
            options["verbose"] = True
        if o in ("-h", "--help"):
            usage()
            return 0
        if o == "--format":
            options['format'] = a
        if o == "-s":
            options['strip'] = a
            sys.stderr.write("Stripping all dashes from %s.\n" % a)
        if o in ("-t", "--threads"):
            options['threads'] = int(a)
            if not options['threads'] >= 1:
                usage()
                return 1
    # tail
    options['phylotree'] = pt_parse_file(tail[0])
    options['leafmap']   = pt_create_map(options['phylotree'])
    # call main with files as argument
    if options['format'] == 'fasta':
        main_fasta(tail[1:])
    elif options['format'] == 'maf':
        main_maf(tail[1:])
    else:
        usage()
        return 1
    return 0

if __name__ == "__main__":
    sys.exit(__main__())
