#! /usr/bin/env python

# Copyright (C) 2011 Philipp Benner
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import ConfigParser
import getopt
import os
import math
import sys

from Bio                    import AlignIO

from tfbayes.fasta          import *
from tfbayes.cluster        import *

# global options
# ------------------------------------------------------------------------------

sampler_config = {
    }

options = {
    'format'         : 'maf',
    'species'        : None,
    'revcomp'        : False,
    'threshold'      : 20.0,
    'load'           : None,
    'verbose'        : False,
    }

# usage
# ------------------------------------------------------------------------------

def usage():
    """Print usage."""
    print
    print "tfbayes-scan [option]... PWM SEQUENCES..."
    print
    print "Scan a set of fasta sequences or multiple alignments in maf format for"
    print "sequences that match the pwm. If fasta files are used, then all sequences"
    print "in the fasta files are scanned. For maf files, only the sequences of a"
    print "reference species is scanned. Use `tfbayes-export-cluster' to obtain the"
    print "PWM from a cluster."
    print
    print "Options:"
    print "       --format=STR               - format of the input file(s) (fasta or maf)"
    print "                                    [default: maf]"
    print "       --species=NAME             - use species as reference (required for alignments)"
    print "   -r                             - scan for the reverse complement"
    print "       --load=FILE_NAME           - load motifs from file"
    print "       --threshold=VALUE"
    print
    print "   -h, --help                     - print help"
    print "   -v, --verbose                  - be verbose"
    print

# scan sequences file
# ------------------------------------------------------------------------------

# use yield here!!

def scan_fasta(pwm, fasta_file):
    if options['revcomp']:
        pwm = tools.reverse_complement(pwm)
    parser = fasta.parser(fasta_file)
    length = len(pwm[0])
    hits = 0
    while 1:
        description, sequence = parser.read_sequence()
        if not sequence:
            break
        for j in range(0, len(sequence)-length):
            sub_sequence = sequence[j:j+length]
            score = tools.compute_score(pwm, sub_sequence)
            if score > options['threshold']:
                hits += 1
                if len(description) >= 3:
                    print "(%15s,%12s,%05i,%3.5f): %s" % (description[0], description[2], j, score, sub_sequence)
                else:
                    print "(%30s,%05i,%3.5f): %s" % (description[0], j, score, sub_sequence)
    print "Found %d sequences." % hits
    return tools.compute_frequencies(counts), hits+1

# scan alignments (maf) or simple fasta sequences
# ------------------------------------------------------------------------------

def scan_maf_files(pwm, maf_files):
    for maf_file in maf_files:
        alignment_list = AlignIO.parse(maf_file, 'maf')
        for alignment in alignment_list:
            scan_alignment(pwm, alignment)

def scan_fasta_files(pwm, fasta_files):
    for fasta_file in fasta_files:
        scan_fasta(pwm, fasta_file)

def scan_sequences_files(pwm, sequences_files):
    if options['format'] == 'maf':
        scan_maf_files(pwm, sequences_files)
    elif options['format'] == 'fasta':
        scan_fasta_files(pwm, sequences_files)
    else:
        raise ValueError("Unknown sequences format.")

# main
# ------------------------------------------------------------------------------

def main(pwm_file, sequences_files):
    pwm = parse_pwm(pwm_file)
    scan_sequences_files(pwm, sequences_files)

# __main__
# ------------------------------------------------------------------------------

def __main__():
    global options
    try:
        longopts   = ["format=", "load=", "species=", "threshold=", "help", "verbose"]
        opts, tail = getopt.getopt(sys.argv[1:], "r", longopts)
    except getopt.GetoptError:
        usage()
        return 2
    output = None
    for o, a in opts:
        if o in ("-v", "--verbose"):
            sys.stderr.write("Verbose mode turned on.\n")
            options["verbose"] = True
        if o in ("-h", "--help"):
            usage()
            return 0
        if o == "--format":
            options['format'] = a
        if o == "--species":
            options['species'] = a
        if o == "--threshold":
            options['threshold'] = float(a)
        if o == "-r":
            options['revcomp'] = True
    if len(tail) < 2:
        usage()
        return 1
    # if format is maf then we need to know the reference
    # species
    if options['format'] is 'maf' and options['species'] is None:
        usage()
        return 1
    # call main
    pwm_file        = tail[0]
    sequences_files = tail[1:]
    main(pwm_file, sequences_files)

if __name__ == "__main__":
    sys.exit(__main__())
