#! /usr/bin/env python

# Copyright (C) 2011 Philipp Benner
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import ConfigParser
import getopt
import math
import os
import re
import subprocess
import sys
import Bio.Motif as Motif

from tfbayes.cluster import *

# global options
# ------------------------------------------------------------------------------

options = {
    'join'        : False,
    'revcomp'     : False,
    'verbose'     : False,
    }

# usage
# ------------------------------------------------------------------------------

def usage():
    """Print usage."""
    print
    print "tfbayes-motifformat [option]... FILE"
    print
    print "Options:"
    print "   -j, --join                     - join plots with pdftk"
    print
    print "   -h, --help                     - print help"
    print "   -v, --verbose                  - be verbose"
    print

# parse results config
# ------------------------------------------------------------------------------

def parse_motif(fin, name, output_file):
    position = fin.tell()
    pattern  = re.compile('^[ \t]*([0-9.]+)[ \t]+([0-9.]+)[ \t]+([0-9.]+)[ \t]+([0-9.]+)[ \t]+([0-9.]+)[ \t]*;?[ \t]*$')
    motif    = [[],[],[],[]]
    while True:
        line = fin.readline()
        if not line:
            break
        result = pattern.match(line)
        if result:
            # rescale the expectations since we only use the first four
            tmp = [float(result.group(1)), float(result.group(2)),
                   float(result.group(3)), float(result.group(4))]
            tmp = map(lambda x: x/sum(tmp), tmp)
            motif[0].append(tmp[0])
            motif[1].append(tmp[1])
            motif[2].append(tmp[2])
            motif[3].append(tmp[3])
            position = fin.tell()
        else:
            fin.seek(position)
            break
    plot.plot_motif(motif, output_file, name)

def join_plots(basename, files):
    cmd = 'pdftk %s cat output %s.pdf' % (' '.join(files), basename)
    print cmd
    subprocess.call(cmd, shell=True)
    cmd = 'rm -f %s' % ' '.join(files)
    print cmd
    subprocess.call(cmd, shell=True)

def parse_motifformat(file_name):
    fin = open(file_name,   'r')
    pattern = re.compile('^>(.*)$')
    output_base = os.path.splitext(file_name)[0]
    idx = 0
    files = []
    while True:
        line = fin.readline()
        if not line:
            break
        result = pattern.match(line)
        if result:
            output_file = '%s_%s-%d.pdf' % (output_base, result.group(1), idx)
            parse_motif(fin, result.group(1), output_file)
            files.append(output_file)
            idx += 1
        else:
            print "Invalid file format."
            exit(1)
    fin.close()
    if options['join']:
        join_plots(output_base, files)

# main
# ------------------------------------------------------------------------------

def main():
    global options
    try:
        longopts   = ["join", "help", "verbose"]
        opts, tail = getopt.getopt(sys.argv[1:], "jhv", longopts)
    except getopt.GetoptError:
        usage()
        return 2
    output = None
    for o, a in opts:
        if o in ("-v", "--verbose"):
            sys.stderr.write("Verbose mode turned on.\n")
            options["verbose"] = True
        if o in ("-h", "--help"):
            usage()
            return 0
        if o in ("-j", "--join"):
            options['join'] = True
    if len(tail) == 1:
        parse_motifformat(*tail)
    else:
        usage()
        return 1
    return 0

if __name__ == "__main__":
    sys.exit(main())
