#! /usr/bin/env python

# Copyright (C) 2011-2014 Philipp Benner
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# imports
# ------------------------------------------------------------------------------

import re
import math
import time
import ConfigParser
import sys
import getopt
import os

import numpy               as     np
import numpy.random.mtrand as     mt
import numpy.random        as     rd

from tfbayes.fasta  import *
from tfbayes.config import *

def importMatplotlib(backend=None):
    global pyplot
    global NonUniformImage
    global PdfPages
    global patches
    global path
    from matplotlib import use
    if backend:
        use(backend)
    import matplotlib.pyplot   as     pyplot
    from   matplotlib.image    import NonUniformImage
    from   matplotlib.backends.backend_pdf import PdfPages
    import matplotlib.patches  as     patches
    import matplotlib.path     as     path

# global options
# ------------------------------------------------------------------------------

sampler_config = default_sampler_config()
results_config = default_results_config()

options = {
    'cluster-sizes' : False,
    'save'          : None,
    'verbose'       : False,
    }

# usage
# ------------------------------------------------------------------------------

def usage():
    """Print usage."""
    print
    print "tfbayes-plot [option]... SAMPLER_CONFIG"
    print
    print "This program plots the log posterior and number of clusters of"
    print "a sampling run."
    print
    print "Options:"
    print "   -c                             - plot cluster sizes as well"
    print "   -s, --save=FILE                - save plot to FILE"
    print
    print "   -h, --help                     - print help"
    print "   -v, --verbose                  - be verbose"
    print

# plot
# ------------------------------------------------------------------------------

def get_cluster_sizes(i, n):
    cluster_sizes = []
    # extract cluster sizes from sampler i
    for j in range(i, len(results_config['sampling_history'].cluster_sizes), n):
        cluster_sizes.append(results_config['sampling_history'].cluster_sizes[j].export())
    return cluster_sizes

def plot_cluster_sizes(ax, cluster_sizes, ymax = None):
    x = []
    y = []
    for i in range(len(cluster_sizes)):
        x.extend([i]*len(cluster_sizes[i]))
        y.extend(cluster_sizes[i])
    ax.scatter(x, y, c="black", edgecolors='None', s=2, alpha=0.3)
    if ymax:
        ax.set_ylim(0, ymax)
    ax.set_xlim(0, len(cluster_sizes))

def plot_result2(results_config, show):
    fig = pyplot.figure()
    fig.subplots_adjust(left=0.15)
    # create subplots
    n    = sampler_config.population_size
    rows = math.floor(math.sqrt(n))
    cols = math.ceil (math.sqrt(n))
    ax   = [None] * n
    m    = max(map(max, results_config['sampling_history'].cluster_sizes))
    for i in range(n):
        cluster_sizes = get_cluster_sizes(i, n)
        ax[i] = fig.add_subplot(rows, cols, i)
        plot_cluster_sizes(ax[i], cluster_sizes, ymax=m+1)
    show()

def plot_result1(results_config, show):
    fig = pyplot.figure()
    fig.subplots_adjust(left=0.15)
    ax1 = fig.add_subplot(3,1,1)
    ax2 = fig.add_subplot(3,1,2)
    ax3 = fig.add_subplot(3,1,3)
    ax1.set_ylabel("log posterior")
    ax2.set_ylabel("components")
    ax3.set_ylabel("temperature")
    for l in results_config['sampling_history'].posterior:
        p1 = ax1.plot(l)
    for c in results_config['sampling_history'].components:
        p2 = ax2.plot(c)
    for t in results_config['sampling_history'].temperature:
        p3 = ax3.plot(t)
    ax3.set_ylim(0, ax3.get_ylim()[1])
    show()

def plot_result(results_config):
    if options['save']:
        importMatplotlib('Agg')
        pp    = PdfPages(options['save'])
        show  = pp.savefig
        close = pp.close
    else:
        importMatplotlib()
        show  = pyplot.show
        close = None
    plot_result1(results_config, show)
    if options['cluster-sizes']:
        plot_result2(results_config, show)
    if close:
        close()

# main
# ------------------------------------------------------------------------------

def main(sampler_config_file):
    parse_sampler_config(sampler_config_file, sampler_config)
    results_config_file = sampler_config.save
    parse_results_config(results_config_file, results_config, False)
    plot_result(results_config)

# __main__
# ------------------------------------------------------------------------------

def __main__():
    global options
    try:
        longopts   = ["help", "verbose", "save="]
        opts, tail = getopt.getopt(sys.argv[1:], "c", longopts)
    except getopt.GetoptError:
        usage()
        return 2
    output = None
    for o, a in opts:
        if o == "-c":
            options["cluster-sizes"] = True
        if o in ("-v", "--verbose"):
            sys.stderr.write("Verbose mode turned on.\n")
            options["verbose"] = True
        if o in ("-h", "--help"):
            usage()
            return 0
        if o in ("-s", "--save"):
            options['save'] = a
    if not len(tail) == 1:
        usage()
        return 1
    main(*tail)
    return 0

if __name__ == "__main__":
    try:
        sys.exit(__main__())
    except IOError, e:
        sys.stderr.write('%s\n' % e)
        sys.exit(1)
