

plot.entropy <- function(k, t, addHlines=TRUE, ...) {
  plot(t, type="l", xlab="h", ylab="pdf", main=sprintf("k = %d", k), ...)
  if (addHlines && k > 2) {
    for (i in 2:(k-1)) {
      abline(v=log(i))
    }
  }
}

f <- function(t) cbind(t$V1, exp(t$V2))

t2 <- read.table("entropy-approximation-2.csv")
t3 <- read.table("entropy-approximation-3.csv")
t4 <- read.table("entropy-approximation-4.csv")
t5 <- read.table("entropy-approximation-5.csv")
t6 <- read.table("entropy-approximation-6.csv")
t7 <- read.table("entropy-approximation-7.csv")
t8 <- read.table("entropy-approximation-8.csv")
t9 <- read.table("entropy-approximation-9.csv")
t10 <- read.table("entropy-approximation-10.csv")
t11 <- read.table("entropy-approximation-11.csv")
t12 <- read.table("entropy-approximation-12.csv")
t13 <- read.table("entropy-approximation-13.csv")
t14 <- read.table("entropy-approximation-14.csv")
t15 <- read.table("entropy-approximation-15.csv")
t16 <- read.table("entropy-approximation-16.csv")
t17 <- read.table("entropy-approximation-17.csv")
t18 <- read.table("entropy-approximation-18.csv")
t19 <- read.table("entropy-approximation-19.csv")
t20 <- read.table("entropy-approximation-20.csv")
t30 <- read.table("entropy-approximation-30.csv")
t40 <- read.table("entropy-approximation-40.csv")
t50 <- read.table("entropy-approximation-50.csv")

par(mfrow=c(4,5))
plot.entropy(2, t2, log="")
plot.entropy(3, t3, log="")
plot.entropy(4, t4, log="")
plot.entropy(5, t5, log="")
plot.entropy(6, t6, log="")
plot.entropy(7, t7, log="")
plot.entropy(8, t8, log="")
plot.entropy(9, t9, log="")
plot.entropy(10, t10, log="")
plot.entropy(11, t11, log="")
plot.entropy(12, t12, log="")
plot.entropy(13, t13, log="")
plot.entropy(14, t14, log="")
plot.entropy(15, t15, log="")
plot.entropy(16, t16, log="")
plot.entropy(17, t17, log="")
plot.entropy(18, t18, log="")
plot.entropy(19, t19, log="")
plot.entropy(20, t20, log="")

plot(t2, type="l", log="", xlab="h", ylab="pdf", main="k = 2")
plot(t3, type="l", log="", xlab="h", ylab="pdf", main="k = 3")
plot(t4, type="l", log="", xlab="h", ylab="pdf", main="k = 4")
plot(t5, type="l", log="", xlab="h", ylab="pdf", main="k = 5")
plot(t6, type="l", log="", xlab="h", ylab="pdf", main="k = 6")
plot(t7, type="l", log="", xlab="h", ylab="pdf", main="k = 7")
plot(t8, type="l", log="", xlab="h", ylab="pdf", main="k = 8")
plot(t9, type="l", log="", xlab="h", ylab="pdf", main="k = 9")
plot(t10, type="l", log="", xlab="h", ylab="pdf", main="k = 10")
plot(t11, type="l", log="", xlab="h", ylab="pdf", main="k = 11")
plot(t12, type="l", log="", xlab="h", ylab="pdf", main="k = 12")
plot(t13, type="l", log="", xlab="h", ylab="pdf", main="k = 13")
plot(t14, type="l", log="", xlab="h", ylab="pdf", main="k = 14")
plot(t15, type="l", log="", xlab="h", ylab="pdf", main="k = 15")
plot(t16, type="l", log="", xlab="h", ylab="pdf", main="k = 16")
plot(t17, type="l", log="", xlab="h", ylab="pdf", main="k = 17")
plot(t18, type="l", log="", xlab="h", ylab="pdf", main="k = 18")
plot(t19, type="l", log="", xlab="h", ylab="pdf", main="k = 19")
plot(t20, type="l", log="", xlab="h", ylab="pdf", main="k = 20")
#plot(t30, type="l", log="", xlab="h", ylab="pdf", main="k = 30")
#plot(t40, type="l", log="", xlab="h", ylab="pdf", main="k = 40")
#plot(t50, type="l", log="", xlab="h", ylab="pdf", main="k = 50")

par(mfrow=c(4,5))
plot(f(t2), type="l", log="", xlab="h", ylab="pdf", main="k = 2")
plot(f(t3), type="l", log="", xlab="h", ylab="pdf", main="k = 3")
plot(f(t4), type="l", log="", xlab="h", ylab="pdf", main="k = 4")
plot(f(t5), type="l", log="", xlab="h", ylab="pdf", main="k = 5")
plot(f(t6), type="l", log="", xlab="h", ylab="pdf", main="k = 6")
plot(f(t7), type="l", log="", xlab="h", ylab="pdf", main="k = 7")
plot(f(t8), type="l", log="", xlab="h", ylab="pdf", main="k = 8")
plot(f(t9), type="l", log="", xlab="h", ylab="pdf", main="k = 9")
plot(f(t10), type="l", log="", xlab="h", ylab="pdf", main="k = 10")
plot(f(t11), type="l", log="", xlab="h", ylab="pdf", main="k = 11")
plot(f(t12), type="l", log="", xlab="h", ylab="pdf", main="k = 12")
plot(f(t13), type="l", log="", xlab="h", ylab="pdf", main="k = 13")
plot(f(t14), type="l", log="", xlab="h", ylab="pdf", main="k = 14")
plot(f(t15), type="l", log="", xlab="h", ylab="pdf", main="k = 15")
plot(f(t16), type="l", log="", xlab="h", ylab="pdf", main="k = 16")
plot(f(t17), type="l", log="", xlab="h", ylab="pdf", main="k = 17")
plot(f(t18), type="l", log="", xlab="h", ylab="pdf", main="k = 18")
plot(f(t19), type="l", log="", xlab="h", ylab="pdf", main="k = 19")
plot(f(t20), type="l", log="", xlab="h", ylab="pdf", main="k = 20")
#plot(f(t30), type="l", log="", xlab="h", ylab="pdf", main="k = 30")
#plot(f(t40), type="l", log="", xlab="h", ylab="pdf", main="k = 40")
#plot(f(t50), type="l", log="", xlab="h", ylab="pdf", main="k = 50")
