
t2 <- read.table("entropy-approximation-2.csv")
t3 <- read.table("entropy-approximation-3.csv")
t4 <- read.table("entropy-approximation-4.csv")
t5 <- read.table("entropy-approximation-5.csv")
#t6 <- read.table("entropy-approximation-6.csv")
#t7 <- read.table("entropy-approximation-7.csv")
t10 <- read.table("entropy-approximation-10.csv")
t20 <- read.table("entropy-approximation-20.csv")
t30 <- read.table("entropy-approximation-30.csv")
t40 <- read.table("entropy-approximation-40.csv")
t50 <- read.table("entropy-approximation-50.csv")

par(mfrow=c(3,3))
plot(t2, type="l", log="", xlab="h", ylab="pdf", main="k = 2")
plot(t3, type="l", log="", xlab="h", ylab="pdf", main="k = 3")
plot(t4, type="l", log="", xlab="h", ylab="pdf", main="k = 4")
plot(t5, type="l", log="", xlab="h", ylab="pdf", main="k = 5")
#plot(t6, type="l", log="", xlab="h", ylab="pdf", main="k = 6")
#plot(t7, type="l", log="", xlab="h", ylab="pdf", main="k = 7")
plot(t10, type="l", log="", xlab="h", ylab="pdf", main="k = 10")
plot(t20, type="l", log="", xlab="h", ylab="pdf", main="k = 20")
plot(t30, type="l", log="", xlab="h", ylab="pdf", main="k = 30")
plot(t40, type="l", log="", xlab="h", ylab="pdf", main="k = 40")
plot(t50, type="l", log="", xlab="h", ylab="pdf", main="k = 50")
