
t2 <- read.table("entropy-approximation-2.csv")
t3 <- read.table("entropy-approximation-3.csv")
t4 <- read.table("entropy-approximation-4.csv")
t5 <- read.table("entropy-approximation-5.csv")
t6 <- read.table("entropy-approximation-6.csv")
t7 <- read.table("entropy-approximation-7.csv")
#t50 <- read.table("entropy-approximation-50.csv")

par(mfrow=c(2,3))
plot(t2, type="l", xlab="h", ylab="pdf", main="k = 2")
plot(t3, type="l", xlab="h", ylab="pdf", main="k = 3")
plot(t4, type="l", xlab="h", ylab="pdf", main="k = 4")
plot(t5, type="l", xlab="h", ylab="pdf", main="k = 5")
plot(t6, type="l", xlab="h", ylab="pdf", main="k = 6")
plot(t7, type="l", xlab="h", ylab="pdf", main="k = 7")
#plot(t50, type="l", log="y", xlab="h", ylab="pdf", main="k = 50")
