#! /usr/bin/env python

# Copyright (C) 2011, 2012 Philipp Benner
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# imports
# ------------------------------------------------------------------------------

import re
import math
import time
import gobject
import gtk
import sys
import getopt
import os
import ConfigParser

import numpy               as     np
import numpy.random.mtrand as     mt
import numpy.random        as     rd

from tfbayes.config  import *
from tfbayes.fasta   import *
from tfbayes.uipac   import *

def importMatplotlib(backend=None):
    global pyplot
    global NonUniformImage
    global patches
    global path
    from matplotlib import use
    if backend:
        use(backend)
    import matplotlib.pyplot   as     pyplot
    from   matplotlib.image    import NonUniformImage
    import matplotlib.patches  as     patches
    import matplotlib.path     as     path

# local imports
# ------------------------------------------------------------------------------

from tfbayes.dpm.dpm_tfbs_interface import *

# global options
# ------------------------------------------------------------------------------

sampler_config = default_sampler_config()

options = {
    'verbose'             : False
    }

# usage
# ------------------------------------------------------------------------------

def usage():
    """Print usage."""
    print
    print "dpm-tfbs-demo [option]... SAMPLER_CONFIG"
    print
    print "Options:"
    print "   -s, --save=FILE                 - save posterior to FILE"
    print "       --samples=SAMPLES[:BURN_IN] - number of samples [default: 1000:100]"
    print
    print "   -h, --help                      - print help"
    print "   -v, --verbose                   - be verbose"
    print

# Tfbs DPM
# ------------------------------------------------------------------------------

class tfbs_dpm_t():
    def __init__(self, sequences, clusters, input_file):
        self.sequences = sequences
        self.clusters  = clusters
        self.steps     = 0
        dpm_init(sampler_config, input_file)
    def print_clusters(self):
        dpm_print()
    def num_clusters(self):
        return dpm_num_clusters()
    def sample(self, n, burnin):
        dpm_sample(n, burnin)
        self.steps += n
    def plotData(self, ax):
        ax.set_xticks([]); ax.set_yticks([])
        plot_sequences(ax, self.sequences, self.clusters)
    def plotResult(self, ax):
        ax.set_title('Gibbs Sampling')
        ax.set_xticks([]); ax.set_yticks([])
        sequences = np.array(self.sequences)
        clusters = dpm_cluster_assignments()
        plot_sequences(ax, sequences, clusters)
    def plotPosterior(self, ax):
        ax.set_title('Posterior')
        ax.set_xticks([]); ax.set_yticks([])
        X = dpm_get_posterior()
        ax.imshow(X, cmap=pyplot.cm.jet, interpolation='nearest')
    def plotStatistics(self, ax1):
        ax2 = ax1.twinx()
        p1  = ax1.plot(dpm_hist_switches())
        p2  = ax2.plot(dpm_hist_likelihood(), color='green')
        ax1.set_ylabel("Class switches")
        ax2.set_ylabel("Likelihood")
        ax1.set_xlabel("iteration")
        ax1.legend([p1, p2], ["Mean class switches", "Mean likelihood"])

class interactive_tfbs_dpm_t(tfbs_dpm_t):
    def __init__(self, sequences, clusters, input_file, ax2, ax3):
        tfbs_dpm_t.__init__(self, sequences, clusters[:][:], input_file)
        self.plotResult(ax2)
        self.plotPosterior(ax3)
        manager = pyplot.get_current_fig_manager()
        def updatefig(*args):
            try:
                ax2.cla()
                ax3.cla()
                self.sampleInteractively(1)
                self.plotResult(ax2)
                self.plotPosterior(ax3)
                manager.canvas.draw()
                return True
            except StopIteration:
                return False
        gobject.idle_add(updatefig)
    def sampleInteractively(self, n):
        self.sample(n, 0)

# read and write sequences
# ------------------------------------------------------------------------------

def read_sequences(seq_file):
    parser = fasta.parser(seq_file)
    sequences = []
    clusters  = []
    while 1:
        description, sequence = parser.read_sequence()
        if not sequence:
            break
        sequences.append('')
        clusters.append([])
        for m in re.finditer(r'\(([1-9]):([ACGTN]+)\)|[ACGTN]+', sequence):
            if m.group(2):
                clusters[-1].extend([ int(m.group(1)) for i in range(0, len(m.group(2))) ])
                sequences[-1] = sequences[-1] + m.group(2)
            else:
                clusters[-1].extend([ 0 for i in range(0, len(m.group(0))) ])
                sequences[-1] = sequences[-1] + m.group(0)
    return sequences, clusters

def write_sequences(output_file, sequences):
    fp = open(output_file, 'w')
    for idx, sequence in enumerate(sequences):
        fp.write('>sequence_%d\n' % idx)
        for nucleotide in sequence:
            tmp = [0.0, 0.0, 0.0, 0.0, 0.0]
            tmp[DNA.code(nucleotide)] = 1.0
            fp.write('%3.1f %3.1f %3.1f %3.1f %3.1f ;\n' % tuple(tmp))
    fp.close()

# plot
# ------------------------------------------------------------------------------

def cluster_colors(c):
    if c < 5:
        return {
           -1 : 'white',
            0 : 'black',
            1 : 'red',
            2 : 'green',
            3 : 'blue',
            4 : 'yellow'
            }[c]
    else:
        return 'magenta'

def plot_sequences(ax, sequences, clusters):
    ax.set_frame_on(False)
    xn    = max(map(len, sequences))
    yn    = len(sequences)
    yfrom = 0.90
    yto   = yfrom-yn*0.07
    x, y = np.meshgrid(np.arange(0.01, 1.00,  0.99/xn),
                       np.arange(yfrom, yto, -(yfrom-yto)/len(sequences)))
    for sl, cl, p1l, p2l in zip(sequences, clusters, x, y):
        for s, c, p1, p2 in zip(sl, cl, p1l, p2l):
            ax.text(p1, p2, str(s), size=10, rotation=0,
                    ha="center", va="bottom", color=cluster_colors(c), weight='bold')

def prepare_plot():
    importMatplotlib('GTKAgg')
    fig1  = pyplot.figure(linewidth=0,facecolor='white',edgecolor='white')
    ax1   = fig1.add_subplot(3,1,1, title='Sequences')
    ax2   = fig1.add_subplot(3,1,2, title='Gibbs Sampling')
    ax3   = fig1.add_subplot(3,1,3, title='Posterior')
    return ax1, ax2, ax3

# sample
# ------------------------------------------------------------------------------

def sample(sequences, clusters, input_file):
    ax1, ax2, ax3 = prepare_plot()
    dpm = interactive_tfbs_dpm_t(sequences, clusters[:][:], input_file, ax2, ax3)
    dpm.plotData(ax1)
    dpm.sample(0, sampler_config['samples'][1])
    dpm.sampleInteractively(sampler_config['samples'][0])
    pyplot.show()

# main
# ------------------------------------------------------------------------------

def main(input_file):
    # read sequences from .in template
    sequences, clusters = read_sequences(input_file+'.in')
    # write sequences in a format that the sampler understands
    write_sequences(input_file, sequences)
    # and sample
    sample(sequences, clusters, input_file)

# __main__
# ------------------------------------------------------------------------------

def __main__():
    global options
    global sampler_config
    try:
        longopts   = ["help", "verbose", "samples=", "save="]
        opts, tail = getopt.getopt(sys.argv[1:], "i:vh", longopts)
    except getopt.GetoptError:
        usage()
        return 1
    output = None
    if len(tail) != 1:
        usage()
        return 1
    # option default options from config file
    parse_sampler_config(tail[0], sampler_config)
    # override those options with command line arguments
    for o, a in opts:
        if o in ("-v", "--verbose"):
            sys.stderr.write("Verbose mode turned on.\n")
            options["verbose"] = True
        if o in ("-h", "--help"):
            usage()
            return 0
        if o in ("-s", "--save"):
            sampler_config['save'] = a
        if o == "--samples":
            tmp = map(int, a.split(":"))
            if len(tmp) == 2:
                sampler_config["samples"] = tuple(tmp)
            elif len(tmp) == 1:
                sampler_config["samples"] = (tmp[0], 0)
            else:
                usage()
                return 1
    main(sampler_config['seq_file'])
    return 0

if __name__ == "__main__":
    sys.exit(__main__())
