#! /usr/bin/env python

from tfbayes.interface import *
from tfbayes.dpm       import *

Sigma   = matrix([[0.01,0.005],[0.005,0.01]])
Sigma_0 = matrix([[10.0,  0.1],[0.1,  10.0]])
mu_0    = vector([0,0])
pi      = vector([0.27693787, 0.06001137, 0.10600994, 0.00997665])

data = data_gaussian_t(2, Sigma, pi)
dpm  = dpm_gaussian_t (1, Sigma, Sigma_0, mu_0, data)

sampler = dpm_gaussian_sampler_t(dpm, data)
p = dpm.partition()

for subset in p:
    for r in subset:
        print r.index()[0]
